### ISSUE TITLE
Change license to Apache 2.0

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction-job-queue#2]
# Context
## Current license
Our `reaction-job-queue` is currently licensed under GPLv3, a strong “copyleft” license which requires licensing derivative works under the same GPLv3 license. We currently only use the `reaction-job-queue` library in our GPLv3 licensed `reaction` project.

## Licensing Libraries and Utilities
We would like to encourage community contributions to our Open Source projects such as `reaction-job-queue`. It’s unclear if we can use bits of code which are GPLv3 licensed and community contributed in our Apache 2 licensed projects such as the Storefront Starter Kit. While we currently own the copyright to all code inside of the `reaction-job-queue`, if we have and accept contributions from outside our organization, it will be difficult to re-license. Re-licensing would require permission from all rights-holders. 

We've been transitioning other libraries such as the Component Library from GPLv3 to Apache 2.0. I propose that we change this project to use the Apache 2.0 license as well.

## 
We’ve previously made the decision to use the Apache 2 license for the Storefront Starter Kit, and the Component Library. When using a permissive license, it does not make sense for us to use multiple permissive licenses, therefore for this project, if we are to transition to a permissive license, we should use the Apache 2 License.

**Comment by brent-hoover** [comment]
Not 100% relevant and not critical but I've always been bummed that we never properly credited the author of the original package, of which this is merely a port

**Comment by spencern** [comment]
@zenweasel what is the license of the original job queue?

**Comment by janus-reith** [comment]
https://github.com/vsivsi/meteor-job/blob/master/LICENSE

**Comment by janus-reith** [comment]
**MIT/X11 license**:
https://github.com/vsivsi/meteor-job/blob/master/LICENSE
https://github.com/vsivsi/meteor-job-collection/blob/master/LICENSE

**Comment by brent-hoover** [comment]
I think we are in the clear license-wise but I think it would be the right thing to do to put some note in the README or something that this is a port of the original work.

Also maybe _something_ in the README

**Comment by spencern** [comment]
@zenweasel I agree we should do that. Seeing no objections, I'll send a PR to update the license and credit the author.
